name: Semantic release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commitlint_and_release:
    name: Commit lint and release
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@v3.0.0
    with:
      runs-on: ubuntu-latest
      # Since we are following the Yamale major version scheme, we don't want
      # to accidentally release a new major version.
      release-enabled: false
